name: MOTA TECHLINK
logoLight: /logos/mota-techlink-logo-wht.webp
logoDark: /logos/mota-techlink-logo-blk.webp
Icon: /logos/mota-icon-v2.webp
logo: /logos/mota-logo-v2.webp
banner: /images/mota-banner.webp
description: Launch Your Dream Startup with AI Support, Zero Cost and Infinite Scale...
contact:
  email: contract@motaiot.com
  toMail: harling@motaiot.com
  phone: "+1 (917) 310-2808"
  address: 1329 Willoughby Ave Brooklyn, NY 11237-3177, USA
google_map:
  mapCoordinates:
    lat: 40.7065032
    lng: -73.9209374
  mapEnable: true
  mapZoom: 11
  mapMarker: images/beachflag.png
  mapURL: https://www.google.com/maps/place/MOTA+TECHLINK+INC./@40.7065031,-73.9258083,17z/data=!3m1!4b1!4m6!3m5!1s0x4cb5e44496595be9:0x6c229d34b2a8ae32!8m2!3d40.7065032!4d-73.9209374!16s%2Fg%2F11ys91d0m4
links:
  twitter: https://twitter.com/motatechlink
  github: https://github.com/mota-techlink/mota-atom
oauth:
  common:
    - id: google
      label: Google
      icon: /icons/google.svg
      enable: true
    - id: github
      label: GitHub
      icon: /icons/github.svg
      enable: true
    - id: x
      label: X (Twitter)
      icon: /icons/twitter.svg
      enable: true
    - id: facebook
      label: Facebook
      icon: /icons/facebook.svg
      enable: false
    - id: linkedin
      label: linkedin
      icon: /icons/linkedin.svg
      enable: false
  regionSpecific:
    zh:
      - id: wechat
        label: 微信
        icon: /icons/wechat.svg
        enable: false
      - id: alibaba
        label: 阿里
        icon: /icons/alibaba.svg
        enable: false
